core/urls.py
from django.urls import path
from .views import (
    itemView,
    ItemDetailView,
    checkout,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView
)

app_name = 'core'

urlpatterns = [
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('checkout/', checkout, name='products'),
    path('', itemView.as_view(), name='item-list'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),

]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include(('core.urls', 'core'), namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse

# Create your models here.

CATEGORY_CHOICES = [
    ('I', 'Instrument'),
    ('CC', 'CaseCover'),
    ('CS', 'Canes'),
    ('BS', 'Books'),
]


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    description = models.TextField(blank=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    slug = models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_final_price(self):
        return self.get_total_item_price()

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField()

    def __str__(self):
        return self.user.username\


    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

core/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item, OrderItem, Order
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, View
from django.utils import timezone
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class itemView(ListView):
    model = Item
    template_name = "item_list.html"


class OrderSummaryView(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'order_summary.html', context)
        except ObjectDoesNotExist:
            messages.error(self.request, "You don't have an active order.")
            return redirect("/")
    # template_name = 'order_summary.html'


def checkout(request):
    return render(request, "checkout.html")


class ItemDetailView(DetailView):
    model = Item
    template_name = "product.html"


def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
    # проверяем если товар находится в заказе
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, 'This item quantity was updated!')
            print(order_item)
        else:
            messages.info(request, 'This item was added to your cart!')
            order.items.add(order_item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request, 'This item was added to your cart!')
    return redirect("core:product", slug=slug)


def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # проверяем если товар находится в заказе
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            messages.info(request, 'Item was deleted from your cart.')
        else:
            # сообщение, что у юзера нет айтемов в заказе
            messages.info(request, 'User dont have an items in order.')
            return redirect("core:product", slug=slug)
    else:
        #  сообщение у пользователя нет ордеров
        messages.info(request, 'User dont have an active order.')
        return redirect("core:product", slug=slug)
    return redirect("core:product", slug=slug)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <title>Duduk ECommerce</title>
</head>

<body>
    <header id="HOth">
        <a href="#" id="btn">Get order</a>
        <a href="/"><img src="{% static "media/logo.png" %}" width="88px"></a>
        <a href="{% url 'core:order-summary'%}" id="btn">Cart <img src="{% static 'media/cart.png'%}"
                width="15px" /></a>
    </header>
    {% for message in messages %}
    <div id="message">
        <p id="message">{{ message }}</p>
    </div>
    {% endfor %}
    <div id="logg">
        {% if user.is_authenticated %}
        <p>Hello, {{ user}}! </p>
        <hr />
        <br />
        <a id="logout" href="{% url 'account_logout'%}">Logout</a>
        {% else %}
        <a id="login" href="{% url 'account_login'%}">Login</a>
        <a id="signup" href="{% url 'account_signup'%}">Sign up</a>
        {% endif %}
    </div>
    <img src="{% static "media/sale.jpg" %}" id="bigbillboard">
    <a href="#"><img src="{% static "media/lmbd.png" %}" id="billboard"></a>
    <div class="content">
        {% block content  %}
        {% endblock content %}
    </div>
    <footer>
        <table class="ft">
            <tr>
                <td rowspan="6" width="340px" style="text-align: center;"><img id="flogo"
                        src="{% static "media/fooLogo.png" %}" alt=""></td>
                <td>
                    <p>Explore</p>
                </td>
                <td>
                    <p>Visit</p>
                </td>
                <td>
                    <p>Follow</p>
                </td>
                <td>
                    <p>Legal</p>
                </td>
                <td>
                    <p>Cart</p>
                </td>
            </tr>
            <tr>
                <td>Home</td>
                <td rowspan="2">36 Yeznik <br>Koghbatsi St,<br> Yerevan 0002,<br> Armenia</td>
                <td><img src="{% static "media/twitter.png" %}"></td>
                <td>Terms of use</td>
                <td>Next page</td>
            </tr>
            <tr>
                <td>Get Order</td>
                <td><img src="{% static "media/instagram.png" %}"></td>
                <td>Privacy</td>
                <td></td>
            </tr>
            <tr>
                <td>About Duduk</td>
                <td></td>
                <td><img src="{% static "media/facebook.png" %}"></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Cart</td>
                <td>
                    <p>New Business</p>
                </td>
                <td><img src="{% static "media/linkedin.png" %}"></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Contacts</td>
                <td>dMarket@gmail.com<br>+1 949 537 2094</td>
                <td><img src="{% static "media/vkico.png" %}"></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td align="center">© 2020 Duduk Market. All Rights Reserved.</td>
            </tr>
        </table>
    </footer>
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

{% load static %}

<h1>Checkout</h1>

templates/item_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="category">
                <p>Category: </p>
                <a href="#" id="catbat" >Instrument</a>
                <a href="#" id="catbat">Case/Cover</a>
                <a href="#" id="catbat">Canes</a>
                <a href="#" id="catbat">Books</a>
    </div>
  {% for item in object_list %}
  <div class="item">
    <div id="description">
        <h4>{{ item.title}}</h4>
        <p>
          {{ item.description}}
        </p>
        <p id="category">Category: {{ item.get_category_display }}</p>
        <p id="price">${{ item.price }}</p>
        <a class="details" href="{{ item.get_absolute_url}}">Details</a>
    </div>
        <figure class="photo">
          <img src="{% static 'media/duduk.png' %}" alt="{{item.title}}" width="200px">
        </figure>
  </div>
  {% endfor %}
{% endblock content %}

templates/order_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Order summary</h1>
<hr>
<div id="carttables">
    <table width="100%" id="cart_table">
        <thead>
            <tr>
                <td>#</td>
                <td>Item title</td>
                <td>Price</td>
                <td>Quantity</td>
                <td>Total price</td>
            </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
            <tr class="sameH">
                <td>{{ forloop.counter }}</td>
                <td>{{ order_item.item.title }}</td>
                <td>{{ order_item.item.price }}</td>
                <td>{{ order_item.quantity }}</td>
                <td>${{ order_item.get_total_item_price }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="4">Order total:</td>
            <td> ${{ object.get_total }}</td>
        </tr>
        </tbody>
    </table>
</div>
<div style="margin: 39px 2px;"><a href="/checkout/" id="confirm">Confirm Order</a></div>
{% endblock content %}

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<table id="detailTable">
    <tr>
        <td style="background-color: white;"><img id="detailimg" src="{% static 'media/duduk.png'%}"></td>
        <td style="background-color: grey;">
            <span>{{ object.get_category_display }}</span>
            <h1 class="title">{{object.title}}</h1>
            <p class="description">{{object.description}}</p>
            <h3 class="price">Price: ${{object.price}}</h3>
            <a class="add" href="{{ object.get_add_to_cart_url }}">Add to cart</a>
            <a class="del" href="{{ object.get_remove_from_cart_url }}">Remove</a>
        </td>
    </tr>
</table>

{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

<h1>Profile</h1>